apiVersion: build.OpenShift.io/v1
kind: BuildConfig
metadata:
  namespace: pibarrap044-dev
  name: ''
spec:
  output:
    to:
      kind: DockerImage
      name: custom-nginx:latest # add yourimage
  source:
    # Expect a local directory to be streamed to OpenShift as a build source
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      # Find the image build instructions in./Dockerfile
      dockerfilePath: Dockerfile