kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: hello-openshift
  namespace: pibarrap044-dev
  labels:
    app: hello-openshift
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'custom-nginx:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/PedroJesus044/test-openshift-jenkins.git'
    contextDir: simple-nginx
  # triggers:
  #   - type: Generic
  #     generic:
  #       secretReference:
  #         name: test-openshift-jenkins-git-generic-webhook-secret
  #   - type: GitHub
  #     github:
  #       secretReference:
  #         name: test-openshift-jenkins-git-github-webhook-secret
  #   - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: 1
