apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-openshift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-openshift
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
      - name: hello-openshift
        #image: custom-nginx:latest
        image: registry.access.redhat.com/ubi9/python-312
        command: ["/usr/libexec/s2i/run"]
        ports:
        - containerPort: 8080